/**
 * 📚 人文与成长
 * 
 * 阅读过的自我提升、人文著作
 */

export default {
  root: {
    id: 'humanities',
    label: '人文与成长',
    color: '#f59e0b',
    description: '阅读与自我提升',
    src: '/pages/humanities.html',
    content: { summary: '读书、思考、成长。记录值得反复咀嚼的著作与感悟。', tags: ['人文'] },
    children: [
      {
        id: 'self-help',
        label: '自我激励',
        color: '#d97706',
        description: '励志与个人成长经典',
        children: [
          {
            id: 'sheepskin',
            label: '羊皮卷',
            color: '#b45309',
            src: '/pages/humanities/sheepskin.html',
            content: { summary: '奥格·曼狄诺 编著 · 自我激励经典。全书8篇，讲述保持心态、制定目标、坚持不懈、认识自我等人生课题。', tags: ['羊皮卷', '自我激励'] },
          },
          {
            id: 'murphy',
            label: '墨菲定律',
            color: '#0891b2',
            src: '/pages/humanities/murphy.html',
            content: { summary: '阿瑟·布洛赫 提出 · 心理学与职场法则经典，弘丰/编。4章34节，涵盖墨菲定律、因果定律、零和游戏定律、鸟笼效应等经典心理学定律，揭示工作与生活中的隐性规律。', tags: ['墨菲定律', '心理学', '职场法则'] },
            children: [
              // ── 第一章 成功基本法则 ──
              { id: 'murphy-ch1', label: '成功基本法则', color: '#06b6d4', src: '/pages/humanities/murphy.html#ch1' },
              { id: 'murphy-murphy', label: '墨菲定律', color: '#06b6d4', src: '/pages/humanities/murphy.html#murphy' },
              { id: 'murphy-cause', label: '因果定律', color: '#06b6d4', src: '/pages/humanities/murphy.html#cause' },
              { id: 'murphy-emotion', label: '困难与情绪', color: '#06b6d4', src: '/pages/humanities/murphy.html#emotion' },
              { id: 'murphy-sourgrapes', label: '酸葡萄与甜柠檬', color: '#0891b2', src: '/pages/humanities/murphy.html#sourgrapes' },
              { id: 'murphy-diminish', label: '幸福递减定律', color: '#0891b2', src: '/pages/humanities/murphy.html#diminish' },
              { id: 'murphy-weber', label: '贝勃定律', color: '#0891b2', src: '/pages/humanities/murphy.html#weber' },
              { id: 'murphy-happiness', label: '幸福的源泉', color: '#0891b2', src: '/pages/humanities/murphy.html#happiness' },
              { id: 'murphy-wildhorse', label: '野马结局', color: '#0d9488', src: '/pages/humanities/murphy.html#wildhorse' },
              { id: 'murphy-carroll', label: '卡瑞尔公式', color: '#0d9488', src: '/pages/humanities/murphy.html#carroll' },
              // ── 第二章 成功竞争法则 ──
              { id: 'murphy-ch2', label: '成功竞争法则', color: '#0d9488', src: '/pages/humanities/murphy.html#ch2' },
              { id: 'murphy-zero', label: '零和游戏定律', color: '#0d9488', src: '/pages/humanities/murphy.html#zero' },
              { id: 'murphy-stress', label: '压力与动力', color: '#7c3aed', src: '/pages/humanities/murphy.html#stress' },
              { id: 'murphy-porter', label: '波特法则', color: '#7c3aed', src: '/pages/humanities/murphy.html#porter' },
              { id: 'murphy-contingency', label: '权变理论', color: '#7c3aed', src: '/pages/humanities/murphy.html#contingency' },
              { id: 'murphy-davidow', label: '达维多定律', color: '#7c3aed', src: '/pages/humanities/murphy.html#davidow' },
              { id: 'murphy-jouffret', label: '儒佛尔定律', color: '#7c3aed', src: '/pages/humanities/murphy.html#jouffret' },
              { id: 'murphy-feith', label: '费斯法则', color: '#7c3aed', src: '/pages/humanities/murphy.html#feith' },
              { id: 'murphy-smith', label: '史密斯原则', color: '#7c3aed', src: '/pages/humanities/murphy.html#smith' },
              { id: 'murphy-rogers', label: '罗杰斯论断', color: '#7c3aed', src: '/pages/humanities/murphy.html#rogers' },
              // ── 第三章 成功人际关系法则 ──
              { id: 'murphy-ch3', label: '人际关系法则', color: '#7c3aed', src: '/pages/humanities/murphy.html#ch3' },
              { id: 'murphy-first', label: '首因效应', color: '#7c3aed', src: '/pages/humanities/murphy.html#first' },
              { id: 'murphy-hedgehog', label: '刺猬法则', color: '#0891b2', src: '/pages/humanities/murphy.html#hedgehog' },
              { id: 'murphy-project', label: '投射效应', color: '#0891b2', src: '/pages/humanities/murphy.html#project' },
              { id: 'murphy-selfexpose', label: '自我暴露定律', color: '#0891b2', src: '/pages/humanities/murphy.html#selfexpose' },
              { id: 'murphy-stereotype', label: '刻板效应', color: '#0891b2', src: '/pages/humanities/murphy.html#stereotype' },
              { id: 'murphy-reciprocal', label: '互惠定律', color: '#06b6d4', src: '/pages/humanities/murphy.html#reciprocal' },
              { id: 'murphy-empathy', label: '换位思考', color: '#06b6d4', src: '/pages/humanities/murphy.html#empathy' },
              { id: 'murphy-silence', label: '沉默定律', color: '#06b6d4', src: '/pages/humanities/murphy.html#silence' },
              { id: 'murphy-need', label: '需求定律', color: '#06b6d4', src: '/pages/humanities/murphy.html#need' },
              // ── 第四章 成功职场法则 ──
              { id: 'murphy-ch4', label: '成功职场法则', color: '#06b6d4', src: '/pages/humanities/murphy.html#ch4' },
              { id: 'murphy-mushroom', label: '蘑菇定律', color: '#06b6d4', src: '/pages/humanities/murphy.html#mushroom' },
              { id: 'murphy-confidence', label: '自信定律', color: '#06b6d4', src: '/pages/humanities/murphy.html#confidence' },
              { id: 'murphy-frog', label: '青蛙法则', color: '#06b6d4', src: '/pages/humanities/murphy.html#frog' },
              { id: 'murphy-birdcage', label: '鸟笼效应', color: '#06b6d4', src: '/pages/humanities/murphy.html#birdcage' },
              { id: 'murphy-rooney', label: '鲁尼恩定律', color: '#06b6d4', src: '/pages/humanities/murphy.html#rooney' },
              { id: 'murphy-chain', label: '链状效应', color: '#06b6d4', src: '/pages/humanities/murphy.html#chain' },
              { id: 'murphy-feedback', label: '反馈效应', color: '#06b6d4', src: '/pages/humanities/murphy.html#feedback' },
            ],
          },
        ],
      },
      {
        id: 'social',
        label: '社交与人际',
        color: '#0ea5e9',
        description: '人际交往与沟通技巧',
        children: [
          {
            id: 'weakness',
            label: '人性的弱点',
            color: '#0284c7',
            src: '/pages/humanities/weakness.html',
            content: { summary: '戴尔·卡耐基 著 · 人际关系经典。4章22篇，讲述如何与人相处、赢得他人好感与信任。', tags: ['人性的弱点', '卡耐基'] },
          },
        ],
      },
      {
        id: 'philosophy',
        label: '哲学与世界观',
        color: '#8b5cf6',
        description: '哲思经典与世界观塑造',
        children: [
          {
            id: 'daodejing',
            label: '道德经',
            color: '#7c3aed',
            src: '/pages/humanities/daodejing.html',
            content: { summary: '老子 著 · 道家根本经典。81章，以"道"为核心，阐述天地万物变化的根本规律与处世智慧。', tags: ['道德经', '老子', '道家'] },
          },
        ],
      },
      {
        id: 'strategy',
        label: '兵法与谋略',
        color: '#dc2626',
        description: '兵家经典与战略智慧',
        children: [
          {
            id: 'sunzi',
            label: '孙子兵法',
            color: '#dc2626',
            src: '/pages/humanities/sunzi.html',
            content: { summary: '孙武 著 · 兵家根本经典。13篇，以"计"为首，系统阐述战争规律与战略智慧。', tags: ['孙子兵法', '孙武', '兵家'] },
            children: [
              { id: 'sunzi-shiji', label: '计篇', color: '#dc2626', src: '/pages/humanities/sunzi.html#shiji' },
              { id: 'sunzi-zuozhan', label: '作战篇', color: '#dc2626', src: '/pages/humanities/sunzi.html#zuozhan' },
              { id: 'sunzi-mougong', label: '谋攻篇', color: '#dc2626', src: '/pages/humanities/sunzi.html#mougong' },
              { id: 'sunzi-xing', label: '形篇', color: '#dc2626', src: '/pages/humanities/sunzi.html#xing' },
              { id: 'sunzi-shi', label: '势篇', color: '#dc2626', src: '/pages/humanities/sunzi.html#shi' },
              { id: 'sunzi-xushi', label: '虚实篇', color: '#dc2626', src: '/pages/humanities/sunzi.html#xushi' },
              { id: 'sunzi-junzheng', label: '军争篇', color: '#b91c1c', src: '/pages/humanities/sunzi.html#junzheng' },
              { id: 'sunzi-jiubian', label: '九变篇', color: '#b91c1c', src: '/pages/humanities/sunzi.html#jiubian' },
              { id: 'sunzi-xingjun', label: '行军篇', color: '#b91c1c', src: '/pages/humanities/sunzi.html#xingjun' },
              { id: 'sunzi-dixing', label: '地形篇', color: '#991b1b', src: '/pages/humanities/sunzi.html#dixing' },
              { id: 'sunzi-jiudi', label: '九地篇', color: '#991b1b', src: '/pages/humanities/sunzi.html#jiudi' },
              { id: 'sunzi-huogong', label: '火攻篇', color: '#7f1d1d', src: '/pages/humanities/sunzi.html#huogong' },
              { id: 'sunzi-yongjian', label: '用间篇', color: '#7f1d1d', src: '/pages/humanities/sunzi.html#yongjian' },
            ],
          },
          {
            id: '36ji',
            label: '三十六计',
            color: '#059669',
            src: '/pages/humanities/36ji.html',
            content: { summary: '檀道济（传）著 · 兵家谋略经典。6套36计，每计含解语、按语、战例。以"走为上策"收尾，体系自胜战至败战。', tags: ['三十六计', '兵家', '谋略'] },
            children: [
              { id: '36ji-shengzhan', label: '胜战计', color: '#059669', src: '/pages/humanities/36ji.html#shengzhan' },
              { id: '36ji-dizhan', label: '敌战计', color: '#047857', src: '/pages/humanities/36ji.html#dizhan' },
              { id: '36ji-gongzhan', label: '攻战计', color: '#047857', src: '/pages/humanities/36ji.html#gongzhan' },
              { id: '36ji-hunzhan', label: '混战计', color: '#065f46', src: '/pages/humanities/36ji.html#hunzhan' },
              { id: '36ji-bingzhan', label: '并战计', color: '#065f46', src: '/pages/humanities/36ji.html#bingzhan' },
              { id: '36ji-baizhan', label: '败战计', color: '#064e3b', src: '/pages/humanities/36ji.html#baizhan' },
            ],
          },
        ],
      },
    ],
  },
  relations: [],
}
